{"name": "test_login[login1]", "status": "failed", "statusDetails": {"message": "AssertionError: 失败原因：密码为空\nassert False", "trace": "login = False\n\n    @pytest.mark.parametrize(\"login\", test_user_data, indirect=True)\n    def test_login(login):\n        '''登录用例'''\n        a = login\n        print(\"测试用例中 login 的返回值:%s\" % a)\n>       assert a, \"失败原因：密码为空\"\nE       AssertionError: 失败原因：密码为空\nE       assert False\n\ntest_demo14.py:29: AssertionError"}, "description": "登录用例", "parameters": [{"name": "login", "value": "{'user': 'admin1', 'psw': ''}"}], "start": 1615054278864, "stop": 1615054278864, "uuid": "a8211a56-dab3-4550-9937-60224a109165", "historyId": "91ad3a2459f936da22d181501c513262", "fullName": "test_demo14#test_login[login1]", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_demo14"}, {"name": "subSuite"}, {"name": "host", "value": "LHL"}, {"name": "thread", "value": "22228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo14"}]}